import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Row, Col, Layout, Menu } from 'antd';

import PostCard from '../components/PostCard';
import Categories from '../components/Categories';
import PostWidget from '../components/PostWidget';
import Header from '../components/Header';
import { Content, Footer } from 'antd/lib/layout/layout';


const posts = [
  { title: 'React Testing', excerpt: 'Learn React Testing' },
  { title: 'Moving to TypeScript', excerpt: 'Learn moving from JavaScript to TypeScript' }
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dev Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="layout" style={{background: 'transparent'}}>
        <Header />
        <Content style={{ padding: '32px 64px', marginTop: "64px", backgroundColor: 'rgba(0,0,0,0.1)'}}>
        <Row justify="space-between">
          <Col span={14}> {/* Main */}
            {posts.map((post, index) => (
            <PostCard post={post} key={post.title} />
            ))}
          </Col>
          <Col span={8} >{/* Side */}
              <div>{/* sticky relative */}
                <PostWidget/>
                <Categories/>
              </div>
          </Col>
        </Row>
        </Content>
        <Footer style={{ textAlign: 'center' }}>Janis Dev Blog ©2022 Created by Janis Schanbacher</Footer>
      </Layout>
    </>
  )
}

export default Home
